(() => {
  'use strict';
  const API = '/api/learning';
  const params = new URLSearchParams(window.location.search);
  const pathParts = window.location.pathname.split('/').filter(Boolean);
  const slug = params.get('course') || (pathParts[0] === 'learn' ? pathParts[1] : '') || 'cyber-basics';
  const course = window.CYBERCLUB_LMS_BY_SLUG?.[slug];
  let lang = localStorage.getItem('club-lang') === 'en' ? 'en' : 'ar';
  let saved = { percent: 0, lastSection: 0, quizScores: {} };
  let current = 0;
  const $ = (id) => document.getElementById(id);
  const allLessons = () => course.modules.flatMap((module, moduleIndex) => module.lessons.map((lesson, lessonIndex) => ({ lesson, module, moduleIndex, lessonIndex })));
  const flat = () => allLessons();
  const text = (value) => typeof value === 'object' ? (value[lang] || value.ar) : value;
  const request = async (path, options = {}) => {
    const response = await fetch(`${API}${path}`, { credentials: 'include', cache: 'no-store', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(result.error || 'تعذر الاتصال بالخادم');
    return result;
  };
  function renderHeader() { document.documentElement.lang = lang; document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'; document.title = `${text(course.ar)} | CyberClub`; $('course-title').textContent = text({ ar: course.ar, en: course.en }); $('course-description').textContent = course.desc; $('course-level').textContent = course.level; $('course-progress').textContent = `${saved.percent || 0}%`; $('course-progress-bar').style.width = `${saved.percent || 0}%`; document.querySelectorAll('[data-course-lang]').forEach((button) => button.classList.toggle('active', button.dataset.courseLang === lang)); }
  function renderModules() { const root = $('modules'); root.innerHTML = course.modules.map((module, moduleIndex) => `<details class="lms-module" ${flat()[current]?.moduleIndex === moduleIndex ? 'open' : ''}><summary><span>${text(module.title)}</span><small>${module.lessons.length} ${lang === 'ar' ? 'دروس' : 'lessons'}</small></summary><div class="lms-module-lessons">${module.lessons.map((lesson, lessonIndex) => { const global = course.modules.slice(0, moduleIndex).reduce((sum, item) => sum + item.lessons.length, 0) + lessonIndex; const done = Boolean(saved.quizScores?.[global]); return `<button class="lms-lesson-link ${global === current ? 'active' : ''}" data-index="${global}" type="button"><span class="lms-check ${done ? 'done' : ''}">${done ? '✓' : ''}</span><span>${text(lesson.title)}</span><small>${text(lesson.typeLabel)}</small></button>`; }).join('')}</div></details>`).join(''); root.querySelectorAll('[data-index]').forEach((button) => button.addEventListener('click', () => { current = Number(button.dataset.index); render(); })); }
  function renderLesson() { const item = flat()[current]; const lesson = item.lesson; const done = Boolean(saved.quizScores?.[current]); $('lesson-breadcrumb').textContent = `${text(item.module.title)}  /  ${text(lesson.title)}`; $('lesson-content').innerHTML = `<div class="lms-lesson-kicker">${text(lesson.typeLabel)} · ${lang === 'ar' ? `الدرس ${current + 1} من ${flat().length}` : `Lesson ${current + 1} of ${flat().length}`}</div><h2>${text(lesson.title)}</h2><p class="lms-lesson-body">${text(lesson.body)}</p><div class="lms-lesson-steps"><h3>${lang === 'ar' ? 'ماذا ستطبق؟' : 'What you will practice'}</h3><ol>${lesson.steps[lang].map((step) => `<li>${step}</li>`).join('')}</ol></div><div class="lms-quiz"><h3>${lang === 'ar' ? 'اختبار قصير' : 'Unit quiz'}</h3><p>${lesson.quiz[lang].question}</p>${lesson.quiz[lang].options.map((option, index) => `<label><input type="radio" name="lms-quiz" value="${index}" ${done ? 'disabled' : ''}> ${option}</label>`).join('')}<span id="quiz-result">${done ? (lang === 'ar' ? 'تم اجتياز هذا الدرس.' : 'Lesson completed.') : ''}</span></div>`; $('previous-lesson').disabled = current === 0; $('complete-lesson').textContent = current === flat().length - 1 ? (lang === 'ar' ? 'إكمال الدورة' : 'Complete course') : (lang === 'ar' ? 'إكمال والانتقال للدرس التالي' : 'Complete and go to next'); $('complete-lesson').disabled = done; }
  function render() { renderHeader(); renderModules(); renderLesson(); }
  async function completeLesson() { const item = flat()[current]; const result = $('quiz-result'); const selected = document.querySelector('input[name="lms-quiz"]:checked'); if (!selected) { result.textContent = lang === 'ar' ? 'اختر إجابة أولًا.' : 'Choose an answer first.'; return; } if (Number(selected.value) !== item.lesson.quiz[lang].correct) { result.textContent = lang === 'ar' ? 'الإجابة غير صحيحة. راجع الدرس وحاول مرة أخرى.' : 'Incorrect. Review the lesson and try again.'; return; } const quizScores = { ...(saved.quizScores || {}), [current]: true }; const percent = Math.round(Object.values(quizScores).filter(Boolean).length / flat().length * 100); try { const response = await request(`/progress/${slug}`, { method: 'PUT', body: JSON.stringify({ percent, lastSection: current + 1, quizScores, language: lang, courseName: text({ ar: course.ar, en: course.en }) }) }); saved = response.progress; if (current < flat().length - 1) current += 1; render(); } catch (error) { result.textContent = error.message; } }
  async function init() { if (!course) { window.location.replace('index.html'); return; } try { const result = await request('/progress'); saved = result.progress?.find((item) => item.courseSlug === slug) || saved; current = Math.min(Number(saved.lastSection || 0), flat().length - 1); render(); } catch (_) { $('course-message').textContent = lang === 'ar' ? 'سجّل الدخول أولًا للوصول إلى بيئة التعلم.' : 'Please sign in to access the learning environment.'; window.setTimeout(() => window.location.replace(`index.html?auth=required&course=${encodeURIComponent(slug)}`), 500); } }
  $('previous-lesson').addEventListener('click', () => { if (current > 0) { current -= 1; render(); } }); $('complete-lesson').addEventListener('click', completeLesson); document.querySelectorAll('[data-course-lang]').forEach((button) => button.addEventListener('click', () => { lang = button.dataset.courseLang; localStorage.setItem('club-lang', lang); render(); })); init();
})();
