/**
 * i18n.js — Arabic/English translation engine.
 *
 * Conventions used across index.html:
 *  - data-i18n="section.key"            -> translates the element's text content
 *  - data-i18n-title="section.key"      -> translates the `title` attribute
 *  - data-i18n-placeholder="section.key"-> translates the `placeholder` attribute
 *  - data-i18n-aria-label="section.key" -> translates the `aria-label` attribute
 *  - data-i18n-alt="section.key"        -> translates the `alt` attribute
 *  - data-i18n-content="section.key"    -> translates the `content` attribute (meta tags)
 *  - data-i18n-list="section.key"       -> key points to an array in the locale file;
 *                                          each <li> is replaced by index
 *  - <button data-lang-switch="ar|en">  -> clicking switches the site language
 *
 * Dynamic content generated by script.js (quiz, games, simulator, password
 * checker, challenges, etc.) listens for the `languagechange` event on
 * `document` and re-renders itself using `window.i18n.t(key)`.
 */
(function () {
  const STORAGE_KEY = 'club-lang';
  const DEFAULT_LANG = 'ar';
  const ATTRS = ['title', 'placeholder', 'aria-label', 'alt', 'content'];

  let currentLang = DEFAULT_LANG;
  let dict = {};

  function getPath(obj, path) {
    return path.split('.').reduce((acc, part) => (acc && acc[part] !== undefined ? acc[part] : undefined), obj);
  }

  function t(key, fallback) {
    const val = getPath(dict, key);
    return val !== undefined ? val : fallback !== undefined ? fallback : key;
  }

  function loadDict(lang) {
    if (!window.LOCALES || !window.LOCALES[lang]) {
      console.error(`i18n: locale "${lang}" not found. Make sure js/locales.js is loaded before js/i18n.js.`);
      return {};
    }
    return window.LOCALES[lang];
  }

  function applyLists() {
    document.querySelectorAll('[data-i18n-list]').forEach((el) => {
      const key = el.getAttribute('data-i18n-list');
      const items = getPath(dict, key);
      if (!Array.isArray(items)) return;
      const lis = el.querySelectorAll(':scope > li');
      lis.forEach((li, i) => {
        if (items[i] !== undefined) li.textContent = items[i];
      });
    });
  }

  function applyStaticTranslations() {
    document.querySelectorAll('[data-i18n]').forEach((el) => {
      const key = el.getAttribute('data-i18n');
      const val = getPath(dict, key);
      if (val !== undefined) el.textContent = val;
    });

    ATTRS.forEach((attr) => {
      document.querySelectorAll(`[data-i18n-${attr}]`).forEach((el) => {
        const key = el.getAttribute(`data-i18n-${attr}`);
        const val = getPath(dict, key);
        if (val !== undefined) el.setAttribute(attr, val);
      });
    });

    applyLists();
  }

  function updateDocumentDirection(lang) {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }

  function updateLangSwitcher(lang) {
    document.querySelectorAll('[data-lang-switch]').forEach((btn) => {
      btn.classList.toggle('active', btn.getAttribute('data-lang-switch') === lang);
    });
    document.querySelectorAll('.lang-switcher').forEach((el) => {
      el.setAttribute('data-active', lang);
    });
  }

  function setLanguage(lang) {
    if (lang !== 'ar' && lang !== 'en') lang = DEFAULT_LANG;
    dict = loadDict(lang);
    currentLang = lang;
    localStorage.setItem(STORAGE_KEY, lang);
    updateDocumentDirection(lang);
    applyStaticTranslations();
    updateLangSwitcher(lang);
    document.dispatchEvent(new CustomEvent('languagechange', { detail: { lang, dict } }));
  }

  function initLangSwitcher() {
    document.querySelectorAll('[data-lang-switch]').forEach((btn) => {
      btn.addEventListener('click', () => {
        setLanguage(btn.getAttribute('data-lang-switch'));
      });
    });
  }

  function init() {
    const saved = localStorage.getItem(STORAGE_KEY) || DEFAULT_LANG;
    initLangSwitcher();
    setLanguage(saved);
  }

  document.addEventListener('DOMContentLoaded', init);

  // Public API used by script.js for dynamically generated content, and by
  // the inline contact-form handler (i18nValue()) in index.html.
  window.i18n = {
    get lang() {
      return currentLang;
    },
    t,
    setLanguage,
  };
  window.i18nValue = t;
})();
